import type { MetadataRoute } from "next";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { routing } from "@/i18n/routing";
import { COUNTRIES as COUNTRY_DATA } from "@/lib/countries";
import { CRYPTO_LIST } from "@/lib/crypto";
import { canonicalPath, SITE_URL } from "@/lib/metadata";
import { ARTICLES } from "@/content/news/articles";

// Git-derived last-modified per route, generated by `scripts/gen-lastmod.mjs`
// in the `prebuild` step. Map shape: { "/gold-price/[karat]": "2026-05-01T..." }
// Falls back to build time when no entry exists.
const LASTMOD_PATH = join(process.cwd(), "data", "lastmod.json");
const LASTMOD: Record<string, string> = existsSync(LASTMOD_PATH)
  ? JSON.parse(readFileSync(LASTMOD_PATH, "utf-8"))
  : {};

function routeLastmod(path: string, fallback: Date): Date {
  // path is a runtime URL like `/gold-price/24k`. lastmod.json is keyed by the
  // page-file route which uses `[karat]` etc. Try literal match first, then
  // strip leading "/" and look up under common dynamic-segment patterns.
  if (LASTMOD[path]) return new Date(LASTMOD[path]);
  // Map runtime → dynamic route key. Examples:
  //   /gold-price/24k       → /gold-price/[karat]
  //   /saudi-arabia/gold-price/21k → /[country]/gold-price/[karat]
  //   /historical-gold-prices/2025 → /historical-gold-prices/[year]
  //   /precious-metals/gold → /precious-metals/[metal]
  //   /cryptocurrency/bitcoin → /cryptocurrency/[coin]
  //   /buy-gold/usa         → /buy-gold/[country]
  //   /buy-gold/usa/coins   → /buy-gold/[country]/[type]
  //   /best-gold-price/usa  → /best-gold-price/[country]
  // Non-default locales carry a prefix (`/en/...`, `/fr/...`) that the
  // lastmod keys never do — strip it so every locale shares one git date.
  const segments = path.split("/").filter(Boolean);
  if (segments[0] && (routing.locales as readonly string[]).includes(segments[0])) segments.shift();
  const guesses = [
    path,
    "/" + segments.join("/"),
    "/" + segments.map((s, i) => {
      // Replace karat/year/coin/metal/country/type tokens with dynamic param.
      if (/^\d{1,4}k$/i.test(s)) return "[karat]";
      if (/^\d{4}$/.test(s)) return "[year]";
      if (i === 0 && COUNTRY_DATA.some((c) => c.slug === s)) return "[country]";
      return s;
    }).join("/"),
  ];
  for (const g of guesses) {
    if (LASTMOD[g]) return new Date(LASTMOD[g]);
  }
  return fallback;
}

const KARATS = ["24k", "22k", "21k", "18k", "14k"];
const COUNTRIES = COUNTRY_DATA.map((c) => c.slug);
const YEARS = Array.from({ length: 2026 - 2000 + 1 }, (_, i) => 2000 + i);

/** Priority MENA + flagship markets get higher sitemap priority. Long-tail
 *  countries get lower priority + lower change frequency to reduce index bloat
 *  and prevent Google from over-recrawling near-duplicate pages. */
const TIER1_COUNTRIES = new Set([
  "saudi-arabia",
  "jordan",
  "uae",
  "egypt",
  "qatar",
  "kuwait",
  "bahrain",
  "usa",
  "uk",
]);

type Freq = "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never";

/**
 * One entry per locale for a locale-agnostic path: Arabic unprefixed, every
 * other locale under `/${locale}/…` (same rule as `canonicalPath`).
 */
function dual(path: string, freq: Freq = "daily", priority = 0.6) {
  return routing.locales.map((locale) => ({
    path: canonicalPath(locale, `/${path}`),
    freq,
    priority,
  }));
}

export default function sitemap(): MetadataRoute.Sitemap {
  const base = SITE_URL;
  const now = new Date();
  const currentYear = now.getFullYear();

  const out: Array<{ path: string; freq: Freq; priority: number }> = dual("", "hourly", 1.0);

  // Karats — top live-price pages. Hourly because prices stream live.
  for (const k of KARATS) out.push(...dual(`gold-price/${k}`, "hourly", 0.9));

  // Country hub — internal-linking entry point for all country markets.
  out.push(...dual("gold-price", "daily", 0.75));

  // Live + spot + chart routes — high-traffic SEO targets.
  out.push(...dual("spot-gold", "hourly", 0.85));
  out.push(...dual("live-gold-price", "hourly", 0.85));
  out.push(...dual("gold-price-chart", "hourly", 0.85));
  out.push(...dual("gold-price-per-ounce", "hourly", 0.8));
  out.push(...dual("gold-price-per-gram", "hourly", 0.8));
  out.push(...dual("gold-price-per-kilo", "hourly", 0.8));

  // Country × Karat (programmatic). Tier-1 markets get higher priority + hourly,
  // long-tail countries get daily + lower priority to control crawl budget.
  for (const c of COUNTRIES) {
    const tier1 = TIER1_COUNTRIES.has(c);
    const freq: Freq = tier1 ? "hourly" : "daily";
    const pr = tier1 ? 0.8 : 0.55;
    for (const k of KARATS) out.push(...dual(`${c}/gold-price/${k}`, freq, pr));
  }

  // Reference + tools — change rarely, but informational queries land here.
  out.push(...dual("gold-silver-ratio", "daily", 0.7));
  out.push(...dual("shanghai-gold-exchange", "daily", 0.65));
  out.push(...dual("gold-calculator", "monthly", 0.6));
  out.push(...dual("widgets", "monthly", 0.4));

  // Precious metals hub + per-metal pages.
  out.push(...dual("precious-metals", "daily", 0.7));
  for (const m of ["gold", "silver", "platinum", "palladium"]) {
    out.push(...dual(`precious-metals/${m}`, "hourly", 0.7));
  }

  // Crypto pages.
  out.push(...dual("cryptocurrency", "hourly", 0.55));
  for (const c of CRYPTO_LIST) out.push(...dual(`cryptocurrency/${c.slug}`, "hourly", 0.5));

  // Best gold price hub + per-country.
  out.push(...dual("best-gold-price", "daily", 0.7));
  for (const c of ["usa", "canada", "singapore", "switzerland", "uk"]) {
    out.push(...dual(`best-gold-price/${c}`, "daily", 0.6));
  }

  // Buy gold pages — bullion coin/bar pricing changes daily-ish.
  // MENA markets (matches Footer's featured set) get tier-1 priority.
  for (const c of ["usa", "uk", "canada", "australia", "saudi-arabia", "uae", "egypt", "morocco"]) {
    const tier1 = TIER1_COUNTRIES.has(c);
    const pHub = tier1 ? 0.75 : 0.65;
    const pSub = tier1 ? 0.65 : 0.55;
    out.push(...dual(`buy-gold/${c}`, "weekly", pHub));
    for (const t of ["coins", "small-coins", "bars"]) {
      out.push(...dual(`buy-gold/${c}/${t}`, "weekly", pSub));
    }
  }

  // Historical years are the site's strongest earners, not archives: Search
  // Console shows "سعر الذهب ٢٠٢٤" alone at 1,142 impressions/28d (position
  // 9.4) and GA4 ranks "Historical Gold Prices · 2026" the #1 page by views.
  // They were tiered 0.3-0.55/yearly, i.e. the lowest on the site — fixed.
  out.push(...dual("historical-gold-prices", "weekly", 0.8));
  for (const y of YEARS) {
    const isCurrent = y === currentYear;
    const recent = currentYear - y <= 5;
    out.push(
      ...dual(
        `historical-gold-prices/${y}`,
        isCurrent ? "daily" : recent ? "weekly" : "monthly",
        isCurrent ? 0.8 : recent ? 0.7 : 0.6,
      ),
    );
  }

  // News — daily.
  out.push(...dual("news", "daily", 0.65));

  // Scholarly research digest — refreshed daily, strong E-E-A-T signal.
  out.push(...dual("research", "daily", 0.65));

  // Editorial articles (each authored by Sadeq, NewsArticle schema).
  for (const a of ARTICLES) {
    out.push(...dual(`news/${a.slug}`, "weekly", 0.7));
  }

  // Editorial / trust pages — change rarely, but signal E-E-A-T.
  out.push(...dual("about", "monthly", 0.5));
  out.push(...dual("about/sadeq", "monthly", 0.6));
  out.push(...dual("about/disclaimer", "monthly", 0.5));
  out.push(...dual("methodology", "monthly", 0.55));
  out.push(...dual("editorial-standards", "monthly", 0.5));
  out.push(...dual("about/privacy", "monthly", 0.4));
  // Contact ranks above the other policy pages on purpose: a reachable
  // publisher is what both readers and ad-network reviewers look for first.
  out.push(...dual("contact", "monthly", 0.55));
  out.push(...dual("terms", "monthly", 0.4));
  out.push(...dual("advertise", "monthly", 0.4));

  // Live-price routes change materially every day (tables, titles, prices),
  // so their lastmod is the current UTC day — accurate and verifiable, which
  // is what Google requires to trust the signal. Editorial routes keep the
  // git-derived date so unchanged pages are not re-crawled.
  const startOfToday = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
  return out.map(({ path, freq, priority }) => ({
    url: `${base}${path}`,
    lastModified: freq === "hourly" ? startOfToday : routeLastmod(path, now),
    changeFrequency: freq,
    priority,
  }));
}
